from nisar_pytools.io import download_urls, find_nisar, open_nisar, stack_gslcs

# _version.py is generated by setuptools-scm at build/install time.
# Fall back so an in-tree run without a prior build still works.
try:
    from nisar_pytools._version import version as __version__
except ImportError:
    __version__ = "0.0.0+unknown"

__all__ = ["download_urls", "find_nisar", "open_nisar", "stack_gslcs", "__version__"]
